version: 2

sources:
  - name: raw_supply_chain
    description: "Raw supply chain data uploaded from CSVs"
    schema: public
    tables:
      - name: orders
        columns:
          - name: order_id
            data_tests:
              - unique
              - not_null
          - name: order_customer_id
            data_tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('raw_supply_chain', 'customers')
                    field: customer_id

      - name: order_items
        columns:
          - name: order_item_id
            data_tests:
              - unique
              - not_null
          - name: order_id
            data_tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('raw_supply_chain', 'orders')
                    field: order_id
          - name: product_id
            data_tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('raw_supply_chain', 'products')
                    field: product_id

      - name: products
        columns:
          - name: product_id
            data_tests:
              - unique
              - not_null
          - name: category_id
            data_tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('raw_supply_chain', 'categories')
                    field: category_id

      - name: customers
        columns:
          - name: customer_id
            data_tests:
              - unique
              - not_null

      - name: categories
        columns:
          - name: category_id
            data_tests:
              - unique
              - not_null
          - name: department_id
            data_tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('raw_supply_chain', 'departments')
                    field: department_id

      - name: departments
        columns:
          - name: department_id
            data_tests:
              - unique
              - not_null
